name: NewbieChat
main: com.gmail.aphymi.newbiechat.NewbieChat
version: 0.8

commands:
  newbies:
    description: Shows a list of online newbies
    usage: '/newbies'
  leave:
    description: Leaves newbie chat room
    usage: '/leave'
  pullnew:
    description: Pulls the sender and specified newbie into a chat room
    usage: '/pullnew <username>'
  pull:
    description: Pulls a player to the sender's chat room
    usage: '/pull <username>'
  chatters:
    description: Displays players in newbie chat rooms
    usage: '/chatters'
  join:
    description: Joins a specific room
    usage: '/join <room number>'


permissions:
  newbiechat.newbies.do:
    description: Lets a player use /newbies
    default: Op
  newbiechat.notnewbie:
    description: Prevents a player from showing up on /newbies
    default: Op
  newbiechat.staff:
    description: Used to show staffers
    default: Op
  newbiechat.rooms.leave:
    description: Lets a player leave a newbie room
    default: Op
  newbiechat.chatters.do:
    description: Lets a player use /chatters
    default: Op
  newbiechat.rooms.pull:
    description: Lets a player pull someone into their newbie room
    default: Op
  newbiechat.rooms.pullnew:
    description: Lets a player create a new newbie room and pull themselves and someone else into it
    default: Op
  newbiechat.rooms.join:
    description: Lets a user join a specified room
    default: Op