name: NewbieChat
version: 1.0.0
description: Provides chat rooms for staff to help new players join the server.
author: Pandomy
main: me.aphymi.newbiechat.NewbieChat

commands:
  ncreload:
    description: Reload the NewbieChat configuration.
    usage: '/ncreload'
    permission: 'newbiechat.reload'
  newbies:
    description: Show a list of online newbies.
    usage: '/newbies'
    permission: 'newbiechat.newbies'
  staff:
    description: Show a list of online staff.
    usage: '/staff'
    permission: 'newbiechat.staff'
  chatters:
    description: Display players in newbie chat rooms.
    usage: '/chatters'
    permission: 'newbiechat.chatters'
  pullnew:
    description: Pull the sender and specified newbie into a chat room.
    usage: '/pullnew <username>'
    permission: 'newbiechat.rooms.pullnew'
  pull:
    description: Pull a player to the sender's chat room.
    usage: '/pull <username>'
    permission: 'newbiechat.rooms.pull'
  join:
    description: Join a specific room.
    usage: '/join <room number>'
    permission: 'newbiechat.rooms.join'
  leave:
    description: Leave newbie chat room.
    usage: '/leave'
    permission: 'newbiechat.rooms.leave'

permissions:
  newbiechat.*:
    description: Give access to all NewbieChat permissions.
    default: Op
    children:
    - newbiechat.notnewbie
    - newbiechat.staffmember
    - newbiechat.staff
    - newbiechat.newbies
    - newbiechat.chatters
    - newbiechat.reload
    - newbiechat.rooms.*
  newbiechat.rooms.*:
    description: Give access to all commands involving leaving/entering rooms.
    default: Op
    children:
    - newbiechat.rooms.pullnew
    - newbiechat.rooms.pull
    - newbiechat.rooms.join
    - newbiechat.rooms.leave
  newbiechat.notnewbie:
    description: Tells NewbieChat that this player isn't a newbie.
    default: Op
  newbiechat.staffmember:
    description: Used to show staff in /staff
    default: Op
  newbiechat.reload:
    description: Let a player use /ncreload
    default: Op
  newbiechat.newbies:
    description: Let a player use /newbies
    default: Op
  newbiechat.staff:
    description: Let a player use /staff
    default: Op
  newbiechat.chatters:
    description: Let a player use /chatters
    default: Op
  newbiechat.rooms.pullnew:
    description: Let a player create a new newbie room and pull themselves and someone else into it
    default: Op
  newbiechat.rooms.pull:
    description: Let a player pull someone into their newbie room
    default: Op
  newbiechat.rooms.join:
    description: Let a user join a specific room
    default: Op
  newbiechat.rooms.leave:
    description: Let a player leave a newbie room
    default: Op
